language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udatube-api-auth  ./udatube-api-auth
  - docker tag udatube-api-auth abdel124/udatube-api-auth:latest
  - docker build -t udatube-api-video ./udatube-api-video
  - docker tag udatube-api-video abdel124/udatube-api-video:latest
  - docker build -t reverseproxy ./reverseproxy
  - docker tag reverseproxy abdel124/reverseproxy:latest


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push abdel124/udagram-api-user
  - docker push abdel124/udagram-api-feed
  - docker push abdel124/udagram-reverseproxy
  - docker push abdel124/udagram-frontend