apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend_auth
  labels:
    run: backend_auth
spec:
  replicas: 2
  selector:
    matchLabels:
      run: backend_auth
  template:
    metadata:
      labels:
        run: backend_auth
    spec:
      containers:
      - name: backend_auth
        image: abdel124/uudatube-api-auth
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: AWS_REGION         
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: JWT_SECRET 
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: AWS_PROFILE 
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: AWS_BUCKET 
        ports:
        - containerPort: 80
        volumeMounts:
          - name: aws-secret
            mountPath: '/home/node/.aws'
            readOnly: true
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret