version: "3"
services:
  reverseproxy:
    build:
      context: ./reverse-proxy
    ports:
      - "80:80"
    image: reverseproxy
    depends_on:
      - backend_auth
      - backend_video
      - backend_comments
  backend_auth:
    build:
      context: ./auth
    ports:
      - "8001:8001"
    image: udatube-api-auth
  backend_video:
    build:
      context: ./video
    ports:
      - "8002:8002"
    image: udatube-api-video
  backend_comments:
    build:
      context: ./comment
    ports:
      - "8003:8003"
    image: udatube-api-comment