apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-comment
  labels:
    run: backend-comment
spec:
  replicas: 2
  selector:
    matchLabels:
      run: backend-comment
  template:
    metadata:
      labels:
        run: backend-comment
    spec:
      containers:
      - name: backend-comment
        image: abdel124/udatube-api-comment
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: AWS_REGION         
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: JWT_SECRET 
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: AWS_PROFILE 
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: AWS_BUCKET 
          - name: CLOUD_FRONT
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: CLOUD_FRONT
        ports:
        - containerPort: 80
        volumeMounts:
          - name: aws-secret
            mountPath: '/root/.aws'
            readOnly: true
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret