apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-front
  labels:
    run: react-ront
spec:
  replicas: 2
  selector:
    matchLabels:
      run: react-front
  template:
    metadata:
      labels:
        run: react-front
    spec:
      containers:
      - name: react-front
        image: abdel124/react_front:latest
        ports:
        - containerPort: 80